---
- name: Deploy Calculator App with Docker
  hosts: localhost
  become: no
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Pull Docker Image
      command: docker pull mtrivedi1410/calculator:latest

    # - name: Run Docker Container
    #   command: docker run -d --name scientific-calculator mydockerhub/scientific-calculator:latest

    # - name: Stop and remove existing container if running
    #   shell: |
    #     docker ps -a --format '{{ "{{" }} .Names {{ "}}" }}' | grep -w calculator && docker stop calculator && docker rm calculator || true
    #   ignore_errors: yes

    - name: Run Java Application Container
      # shell: docker run -it -d --name calculator mtrivedi1410/calculator
      shell: docker run -it -d --name calculator mtrivedi1410/calculator /bin/bash